// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emdzsnwcyyrlaljrrjmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZHpzbndjeXlybGFsanJyam1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzMxODIsImV4cCI6MjA3MjQ0OTE4Mn0.uC-CV3OmaYg2oGa3OS1wQqpu2UyZzM4xGbt2ci38jFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});